ifndef VERILATOR_ENV
VERILATOR_ENV:=1

VERILATOR_FLAGS:= -sv -MMD $(VERILATOR_VERSION_RELATED_FLAGS)
VERILATOR_WARNINGS?=-Wall -Wno-PINCONNECTEMPTY -Wno-UNUSED -Wno-WIDTH -Wno-SELRANGE -Wno-DECLFILENAME
VERILATOR_OPTIMIZATION_FLAG?=-O3

ifdef USING_VERILATOR_CPP
VERILATOR_CPP_TESTBENCH_FLAG?=-exe --cc
VERILATER_FLAGS+=$(VERILATOR_OPTIMIZATION_FLAG) $(VERILATOR_WARNINGS) $(VERILATOR_CPP_TESTBENCH_FLAG)
else
VERILATOR_SV_TESTBENCH_FLAG?=--timing --binary --main
VERILATER_FLAGS+=$(VERILATOR_OPTIMIZATION_FLAG) $(VERILATOR_WARNINGS) $(VERILATOR_SV_TESTBENCH_FLAG)
endif

endif
