# unittest ci in github
name: unittest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: build docker
      run: |
        make unprivileged_verilator
      working-directory: tools/docker
      
    - name: run unittest
      run: |
        USE_DOCKER=1 make run
      working-directory: hardware/riscv64/test


